# Site settings
title: Elaine Lu
email: elainelu98@gmail.com
description: > # tåhis means to ignore newlines until "baseurl:"
  
baseurl: "/" # the subpath of your site, e.g. /blog/
url: "http://eelainelu.com" # the base hostname & protocol for your site

# Build settings
markdown: 
sass:
  style: :compressed

# Content settings
collections:
  projects:
    output: true
    permalink: /projects/:path/